### ISSUE TITLE
std updates

### ISSUE THREAD

**Issue by Ten0** [whentze/drain_filter_polyfill#1]
There have been updates to this file in the std, improving doc and adding a `keep_rest` function:
https://github.com/rust-lang/rust/commits/master/library/alloc/src/vec/drain_filter.rs

Maybe these should be ported over to here?

**Comment by whentze** [comment]
Thanks for notifying!

Addressed in https://github.com/whentze/drain_filter_polyfill/commit/083ba880100444a30a80ff6cc0ce078c664cd6dd

I have just published [version 0.1.3](https://crates.io/crates/drain_filter_polyfill/0.1.3) that includes these changes.
